package com.vpavlov.ups.reversi.client.domains.connection

const val IDENTIFIER = "RVSI"

const val MSG_MAX_LENGTH = 9999999

const val MSG_IDENTIFIER_FIELD_POS = 0

const val MSG_IDENTIFIER_FIELD_LENGTH = 7

const val MSG_LENGTH_FIELD_POS = MSG_IDENTIFIER_FIELD_POS + MSG_IDENTIFIER_FIELD_LENGTH

const val MSG_LENGTH_FIELD_LENGTH = 4

const val MSG_TYPE_FIELD_POS = MSG_LENGTH_FIELD_POS + MSG_LENGTH_FIELD_LENGTH

const val MSG_TYPE_FIELD_LENGTH = 1

const val MSG_SUBTYPE_FIELD_POS = MSG_TYPE_FIELD_POS + MSG_TYPE_FIELD_LENGTH

const val MSG_SUBTYPE_FIELD_LENGTH = 2

const val MSG_STATUS_FIELD_POS = MSG_SUBTYPE_FIELD_POS + MSG_SUBTYPE_FIELD_LENGTH

const val MSG_STATUS_FIELD_LENGTH = 3

const val MSG_HEADER_LENGTH =
    MSG_IDENTIFIER_FIELD_LENGTH + MSG_LENGTH_FIELD_LENGTH + MSG_TYPE_FIELD_LENGTH + MSG_SUBTYPE_FIELD_LENGTH + MSG_STATUS_FIELD_LENGTH